from django.conf.urls import url

from django.views.generic import TemplateView

urlpatterns = [

    # /me pages
    url(r'me/hotel-palas/pregled-hotela/', TemplateView.as_view(template_name='palas/hotel-overview.html')),
    url(r'me/hotel-palas/smjestaj/standardna-dvokrevetna-soba/', TemplateView.as_view(template_name='palas/standard-double.html')),
    url(r'me/hotel-palas/smjestaj/dvokrevetna-soba-sa-pogledom-na-more/', TemplateView.as_view(template_name='palas/double-sea-view.html')),
    url(r'me/hotel-palas/smjestaj/dvokrevetna-soba-sa-pogledom-na-brdo/', TemplateView.as_view(template_name='palas/double-mountain-view.html')),
    url(r'me/hotel-palas-lux/smjestaj/lux-dvokrevetna-soba/', TemplateView.as_view(template_name='palas/lux-double.html')),
    url(r'me/hotel-palas-lux/smjestaj/lux-dvokrevetna-soba-sa-odvojenim-lezajevima/', TemplateView.as_view(template_name='palas/lux-double-separate-beds.html')),
    url(r'me/hotel-palas-lux/smjestaj/lux-apartman-pogled-na-more/', TemplateView.as_view(template_name='palas/lux-sea-view.html')),
    url(r'me/hotel-palas-lux/smjestaj/lux-apartman-pogled-na-brdo/', TemplateView.as_view(template_name='palas/lux-mountain-view.html')),
    url(r'me/hotel-palas/smjestaj/', TemplateView.as_view(template_name='palas/accommodation.html')),
    url(r'me/hotel-palas-lux/smjestaj/', TemplateView.as_view(template_name='palas/accommodation-lux.html')),
    url(r'me/hotel-palas/konferencije/', TemplateView.as_view(template_name='palas/meetings.html')),
    url(r'me/hotel-palas/vjencanja/', TemplateView.as_view(template_name='palas/weddings.html')),
    url(r'me/hotel-palas/restorani/', TemplateView.as_view(template_name='palas/restaurants.html')),
    url(r'me/hotel-palas/plaze-i-bazeni/', TemplateView.as_view(template_name='palas/beaches.html')),
    url(r'me/hotel-palas/wellness-i-spa/', TemplateView.as_view(template_name='palas/wellness.html')),
    url(r'me/hotel-palas/tajlandska-masaza/', TemplateView.as_view(template_name='palas/thai-massage.html')),
    url(r'me/hotel-palas/lokacija/', TemplateView.as_view(template_name='palas/location.html')),
    url(r'me/hotel-palas/', TemplateView.as_view(template_name='palas/hotel-overview.html')),

    # /en pages
    url(r'en/hotel-palas/overview/', TemplateView.as_view(template_name='palas/hotel-overview.html')),
    url(r'en/hotel-palas/rooms-and-suites/standard-double-room/', TemplateView.as_view(template_name='palas/standard-double.html')),
    url(r'en/hotel-palas/rooms-and-suites/double-room-sea-view/', TemplateView.as_view(template_name='palas/double-sea-view.html')),
    url(r'en/hotel-palas/rooms-and-suites/double-room-mountain-view/', TemplateView.as_view(template_name='palas/double-mountain-view.html')),
    url(r'en/hotel-palas-lux/rooms-and-suites/lux-double-room/', TemplateView.as_view(template_name='palas/lux-double.html')),
    url(r'en/hotel-palas-lux/rooms-and-suites/lux-double-room-with-separate-beds/', TemplateView.as_view(template_name='palas/lux-double-separate-beds.html')),
    url(r'en/hotel-palas-lux/rooms-and-suites/lux-suite-sea-view/', TemplateView.as_view(template_name='palas/lux-sea-view.html')),
    url(r'en/hotel-palas-lux/rooms-and-suites/lux-suite-mountain-view/', TemplateView.as_view(template_name='palas/lux-mountain-view.html')),
    url(r'en/hotel-palas/rooms-and-suites/', TemplateView.as_view(template_name='palas/accommodation.html')),
    url(r'en/hotel-palas-lux/rooms-and-suites/', TemplateView.as_view(template_name='palas/accommodation-lux.html')),
    url(r'en/hotel-palas/conference-rooms/', TemplateView.as_view(template_name='palas/meetings.html')),
    url(r'en/hotel-palas/weddings/', TemplateView.as_view(template_name='palas/weddings.html')),
    url(r'en/hotel-palas/restaurants-and-bars/', TemplateView.as_view(template_name='palas/restaurants.html')),
    url(r'en/hotel-palas/beaches-and-pools/', TemplateView.as_view(template_name='palas/beaches.html')),
    url(r'en/hotel-palas/wellness-and-spa/', TemplateView.as_view(template_name='palas/wellness.html')),
    url(r'en/hotel-palas/thai-massage/', TemplateView.as_view(template_name='palas/thai-massage.html')),
    url(r'en/hotel-palas/location/', TemplateView.as_view(template_name='palas/location.html')),
    url(r'en/hotel-palas/', TemplateView.as_view(template_name='palas/hotel-overview.html')),

    # /it pages
    url(r'it/hotel-palas/informazioni-generali/', TemplateView.as_view(template_name='palas/hotel-overview.html')),
    url(r'it/hotel-palas/alloggi/camera-doppia-standard/', TemplateView.as_view(template_name='palas/standard-double.html')),
    url(r'it/hotel-palas/alloggi/camera-doppia-con-vista-mare/', TemplateView.as_view(template_name='palas/double-sea-view.html')),
    url(r'it/hotel-palas/alloggi/camera doppia-con-vista-montagna/', TemplateView.as_view(template_name='palas/double-mountain-view.html')),
    url(r'it/hotel-palas-lux/alloggi/camera-doppia-lux/', TemplateView.as_view(template_name='palas/lux-double.html')),
    url(r'it/hotel-palas-lux/alloggi/camera-doppia-lux-con-letti-separati/', TemplateView.as_view(template_name='palas/lux-double-separate-beds.html')),
    url(r'it/hotel-palas-lux/alloggi/suite-lux-con-vista-mare/', TemplateView.as_view(template_name='palas/lux-sea-view.html')),
    url(r'it/hotel-palas-lux/alloggi/suite-lux-con-vista-montagna/', TemplateView.as_view(template_name='palas/lux-mountain-view.html')),
    url(r'it/hotel-palas/alloggi/', TemplateView.as_view(template_name='palas/accommodation.html')),
    url(r'it/hotel-palas-lux/alloggi/', TemplateView.as_view(template_name='palas/accommodation-lux.html')),
    url(r'it/hotel-palas/sala-conferenze/', TemplateView.as_view(template_name='palas/meetings.html')),
    url(r'it/hotel-palas/matrimoni/', TemplateView.as_view(template_name='palas/weddings.html')),
    url(r'it/hotel-palas/ristoranti-e-bar/', TemplateView.as_view(template_name='palas/restaurants.html')),
    url(r'it/hotel-palas/spiagge-e-piscine/', TemplateView.as_view(template_name='palas/beaches.html')),
    url(r'it/hotel-palas/wellness-e-spa/', TemplateView.as_view(template_name='palas/wellness.html')),
    url(r'it/hotel-palas/massaggio-tailandese/', TemplateView.as_view(template_name='palas/thai-massage.html')),
    url(r'it/hotel-palas/posizione/', TemplateView.as_view(template_name='palas/location.html')),
    url(r'it/hotel-palas/', TemplateView.as_view(template_name='palas/hotel-overview.html')),

    # /de pages
    url(r'de/hotel-palas/hoteluebersicht/', TemplateView.as_view(template_name='palas/hotel-overview.html')),
    url(r'de/hotel-palas/unterkunft/standard-doppelzimmer/', TemplateView.as_view(template_name='palas/standard-double.html')),
    url(r'de/hotel-palas/unterkunft/doppelzimmer-mit-meerblick/', TemplateView.as_view(template_name='palas/double-sea-view.html')),
    url(r'de/hotel-palas/unterkunft/doppelzimmer-mit-blick-auf-die-berge/', TemplateView.as_view(template_name='palas/double-mountain-view.html')),
    url(r'de/hotel-palas-lux/unterkunft/lux-doppelzimmer/', TemplateView.as_view(template_name='palas/lux-double.html')),
    url(r'de/hotel-palas-lux/unterkunft/lux-doppelzimmer-mit-separaten-betten/', TemplateView.as_view(template_name='palas/lux-double-separate-beds.html')),
    url(r'de/hotel-palas-lux/unterkunft/lux-suite-mit-meerblick/', TemplateView.as_view(template_name='palas/lux-sea-view.html')),
    url(r'de/hotel-palas-lux/unterkunft/lux-suite-mit-blick-auf-die-berge/', TemplateView.as_view(template_name='palas/lux-mountain-view.html')),
    url(r'de/hotel-palas/unterkunft/', TemplateView.as_view(template_name='palas/accommodation.html')),
    url(r'de/hotel-palas-lux/unterkunft/', TemplateView.as_view(template_name='palas/accommodation-lux.html')),
    url(r'de/hotel-palas/konferenzraeume/', TemplateView.as_view(template_name='palas/meetings.html')),
    url(r'de/hotel-palas/hochzeitszeremonie/', TemplateView.as_view(template_name='palas/weddings.html')),
    url(r'de/hotel-palas/restaurants-und-bars/', TemplateView.as_view(template_name='palas/restaurants.html')),
    url(r'de/hotel-palas/straende-und-pools/', TemplateView.as_view(template_name='palas/beaches.html')),
    url(r'de/hotel-palas/wellness-und-spa/', TemplateView.as_view(template_name='palas/wellness.html')),
    url(r'de/hotel-palas/thailandische-massage/', TemplateView.as_view(template_name='palas/thai-massage.html')),
    url(r'de/hotel-palas/lage/', TemplateView.as_view(template_name='palas/location.html')),
    url(r'de/hotel-palas/', TemplateView.as_view(template_name='palas/hotel-overview.html')),

    # /fr pages
    url(r'fr/hotel-palas/apercu/', TemplateView.as_view(template_name='palas/hotel-overview.html')),
    url(r'fr/hotel-palas/chambres-et-suites/chambre-double-standard/', TemplateView.as_view(template_name='palas/standard-double.html')),
    url(r'fr/hotel-palas/chambres-et-suites/chambre-double-vue-mer/', TemplateView.as_view(template_name='palas/double-sea-view.html')),
    url(r'fr/hotel-palas/chambres-et-suites/chambre-double-avec-vue-sur-la-montagne/', TemplateView.as_view(template_name='palas/double-mountain-view.html')),
    url(r'fr/hotel-palas-lux/chambres-et-suites/chambre-double-lux/', TemplateView.as_view(template_name='palas/lux-double.html')),
    url(r'fr/hotel-palas-lux/chambres-et-suites/chambre-double-lux-avec-lits-séparés/', TemplateView.as_view(template_name='palas/lux-double-separate-beds.html')),
    url(r'fr/hotel-palas-lux/chambres-et-suites/suite-lux-avec-vue-mer/', TemplateView.as_view(template_name='palas/lux-sea-view.html')),
    url(r'fr/hotel-palas-lux/chambres-et-suites/suite-lux-avec-vue-sur-la-montagne/', TemplateView.as_view(template_name='palas/lux-mountain-view.html')),
    url(r'fr/hotel-palas/chambres-et-suites/', TemplateView.as_view(template_name='palas/accommodation.html')),
    url(r'fr/hotel-palas-lux/chambres-et-suites/', TemplateView.as_view(template_name='palas/accommodation-lux.html')),
    url(r'fr/hotel-palas/salles-de-conference/', TemplateView.as_view(template_name='palas/meetings.html')),
    url(r'fr/hotel-palas/mariages/', TemplateView.as_view(template_name='palas/weddings.html')),
    url(r'fr/hotel-palas/restaurants-et-bars/', TemplateView.as_view(template_name='palas/restaurants.html')),
    url(r'fr/hotel-palas/plages-et-piscines/', TemplateView.as_view(template_name='palas/beaches.html')),
    url(r'fr/hotel-palas/bien-etre-et-spa/', TemplateView.as_view(template_name='palas/wellness.html')),
    url(r'fr/hotel-palas/massage-thai/', TemplateView.as_view(template_name='palas/thai-massage.html')),
    url(r'fr/hotel-palas/localisation/', TemplateView.as_view(template_name='palas/location.html')),
    url(r'fr/hotel-palas/', TemplateView.as_view(template_name='palas/hotel-overview.html')),

    # /ru pages

    url(r'ru/otel-palas/obzor/', TemplateView.as_view(template_name='palas/hotel-overview.html')),
    url(r'ru/hotel-palas/nomera-i-apartamenty/standartnyy-dvukhmestnyy-nomer/', TemplateView.as_view(template_name='palas/standard-double.html')),
    url(r'ru/hotel-palas/nomera-i-apartamenty/dvukhmestnyy-nomer-s-vidom-na-more/', TemplateView.as_view(template_name='palas/double-sea-view.html')),
    url(r'ru/hotel-palas/nomera-i-apartamenty/dvukhmestnyy-nomer-s-vidom-na-gory/', TemplateView.as_view(template_name='palas/double-mountain-view.html')),
    url(r'ru/hotel-palas-lux/nomera-i-apartamenty/dvukhmestnyy-nomer-lyuks/', TemplateView.as_view(template_name='palas/lux-double.html')),
    url(r'ru/hotel-palas-lux/nomera-i-apartamenty/dvukhmestnyy-nomer-lyuks-s-razdelnymi-krovatyami/', TemplateView.as_view(template_name='palas/lux-double-separate-beds.html')),
    url(r'ru/hotel-palas-lux/nomera-i-apartamenty/lyuks-s-vidom-na-more/', TemplateView.as_view(template_name='palas/lux-sea-view.html')),
    url(r'ru/hotel-palas-lux/nomera-i-apartamenty/lyuks-s-vidom-na-gory/', TemplateView.as_view(template_name='palas/lux-mountain-view.html')),
    url(r'ru/otel-palas/nomera-i-apartamenty/', TemplateView.as_view(template_name='palas/accommodation.html')),
    url(r'ru/hotel-palas-lux/nomera-i-apartamenty/', TemplateView.as_view(template_name='palas/accommodation-lux.html')),
    url(r'ru/otel-palas/konferents-zaly/', TemplateView.as_view(template_name='palas/meetings.html')),
    url(r'ru/otel-palas/svadby/', TemplateView.as_view(template_name='palas/weddings.html')),
    url(r'ru/otel-palas/restorany-i-bary/', TemplateView.as_view(template_name='palas/restaurants.html')),
    url(r'ru/otel-palas/plyazhi-i-basseyny/', TemplateView.as_view(template_name='palas/beaches.html')),
    url(r'ru/otel-palas/sauna-i-spa/', TemplateView.as_view(template_name='palas/wellness.html')),
    url(r'ru/otel-palas/tayskiy-massazh/', TemplateView.as_view(template_name='palas/thai-massage.html')),
    url(r'ru/otel-palas/lokaciya/', TemplateView.as_view(template_name='palas/location.html')),
    url(r'ru/otel-palas/', TemplateView.as_view(template_name='palas/hotel-overview.html')),

    ]
