from django.conf.urls import include, url

from django.views.generic import TemplateView

urlpatterns = [
    # /me pages
    url(r'me/hotel-aleksandar-u-budvi/pregled-hotela/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),
    url(r'me/hotel-aleksandar-u-budvi/smjestaj/dvokrevetna-soba/', TemplateView.as_view(template_name='aleksandar/standard-double-terrace.html')),
    url(r'me/hotel-aleksandar-u-budvi/smjestaj/dvokrevetna-soba-sa-terasom/', TemplateView.as_view(template_name='aleksandar/standard-double.html')),
    url(r'me/hotel-aleksandar-u-budvi/smjestaj/comfort-soba-sa-terasom/', TemplateView.as_view(template_name='aleksandar/comfort-double.html')),
    url(r'me/hotel-aleksandar-u-budvi/smjestaj/porodicna-soba/', TemplateView.as_view(template_name='aleksandar/family-room.html')),
    url(r'me/hotel-aleksandar-u-budvi/smjestaj/apartman/', TemplateView.as_view(template_name='aleksandar/large-family-room.html')),
    url(r'me/hotel-aleksandar-u-budvi/smjestaj/', TemplateView.as_view(template_name='aleksandar/accommodation.html')),
    url(r'me/hotel-aleksandar-u-budvi/restorani/', TemplateView.as_view(template_name='aleksandar/restaurants.html')),
    url(r'me/hotel-aleksandar-u-budvi/konferencije/', TemplateView.as_view(template_name='aleksandar/meetings.html')),
    url(r'me/hotel-aleksandar-u-budvi/wellness-i-spa/', TemplateView.as_view(template_name='aleksandar/wellness.html')),
    url(r'me/hotel-aleksandar-u-budvi/plaze-i-bazeni/', TemplateView.as_view(template_name='aleksandar/beaches.html')),
    url(r'me/hotel-aleksandar-u-budvi/lokacija/', TemplateView.as_view(template_name='aleksandar/location.html')),
    url(r'me/hotel-aleksandar-u-budvi/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),

    # /en pages
    url(r'en/hotel-aleksandar-in-budva/overview/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),
    url(r'en/hotel-aleksandar-in-budva/rooms-and-suites/double-twin-room/', TemplateView.as_view(template_name='aleksandar/standard-double-terrace.html')),
    url(r'en/hotel-aleksandar-in-budva/rooms-and-suites/double-twin-room-balcony/', TemplateView.as_view(template_name='aleksandar/standard-double.html')),
    url(r'en/hotel-aleksandar-in-budva/rooms-and-suites/comfort-room-balcony/', TemplateView.as_view(template_name='aleksandar/comfort-double.html')),
    url(r'en/hotel-aleksandar-in-budva/rooms-and-suites/family-room/', TemplateView.as_view(template_name='aleksandar/family-room.html')),
    url(r'en/hotel-aleksandar-in-budva/rooms-and-suites/apartment/', TemplateView.as_view(template_name='aleksandar/large-family-room.html')),
    url(r'en/hotel-aleksandar-in-budva/rooms-and-suites/', TemplateView.as_view(template_name='aleksandar/accommodation.html')),
    url(r'en/hotel-aleksandar-in-budva/restaurants-and-bars/', TemplateView.as_view(template_name='aleksandar/restaurants.html')),
    url(r'en/hotel-aleksandar-in-budva/conference-rooms/', TemplateView.as_view(template_name='aleksandar/meetings.html')),
    url(r'en/hotel-aleksandar-in-budva/wellness-and-spa/', TemplateView.as_view(template_name='aleksandar/wellness.html')),
    url(r'en/hotel-aleksandar-in-budva/beaches-and-pools/', TemplateView.as_view(template_name='aleksandar/beaches.html')),
    url(r'en/hotel-aleksandar-in-budva/location/', TemplateView.as_view(template_name='aleksandar/location.html')),
    url(r'en/hotel-aleksandar-in-budva/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),

    # /it pages
    url(r'it/hotel-aleksandar-a-budva/informazioni-generali/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),
    url(r'it/hotel-aleksandar-a-budva/alloggi/camera-matrimoniale-doppia/', TemplateView.as_view(template_name='aleksandar/standard-double-terrace.html')),
    url(r'it/hotel-aleksandar-a-budva/alloggi/camera-matrimoniale-doppia-con-balcone/', TemplateView.as_view(template_name='aleksandar/standard-double.html')),
    url(r'it/hotel-aleksandar-a-budva/alloggi/camera-comfort-con-balcone/', TemplateView.as_view(template_name='aleksandar/comfort-double.html')),
    url(r'it/hotel-aleksandar-a-budva/alloggi/camera-familiare/', TemplateView.as_view(template_name='aleksandar/family-room.html')),
    url(r'it/hotel-aleksandar-a-budva/alloggi/appartamento/', TemplateView.as_view(template_name='aleksandar/large-family-room.html')),
    url(r'it/hotel-aleksandar-a-budva/alloggi/', TemplateView.as_view(template_name='aleksandar/accommodation.html')),
    url(r'it/hotel-aleksandar-a-budva/ristoranti-e-bar/', TemplateView.as_view(template_name='aleksandar/restaurants.html')),
    url(r'it/hotel-aleksandar-a-budva/sala-conferenze/', TemplateView.as_view(template_name='aleksandar/meetings.html')),
    url(r'it/hotel-aleksandar-a-budva/wellness-e-spa/', TemplateView.as_view(template_name='aleksandar/wellness.html')),
    url(r'it/hotel-aleksandar-a-budva/spiagge-e-piscine/', TemplateView.as_view(template_name='aleksandar/beaches.html')),
    url(r'it/hotel-aleksandar-a-budva/posizione/', TemplateView.as_view(template_name='aleksandar/location.html')),
    url(r'it/hotel-aleksandar-a-budva/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),

    # /de pages
    url(r'de/hotel-aleksandar-in-budva/hoteluebersicht/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),
    url(r'de/hotel-aleksandar-in-budva/unterkunft/doppel-zweibettzimmer/', TemplateView.as_view(template_name='aleksandar/standard-double-terrace.html')),
    url(r'de/hotel-aleksandar-in-budva/unterkunft/doppel-zweibettzimmer-mit-balkon/', TemplateView.as_view(template_name='aleksandar/standard-double.html')),
    url(r'de/hotel-aleksandar-in-budva/unterkunft/komfort-doppelzimmer/', TemplateView.as_view(template_name='aleksandar/comfort-double.html')),
    url(r'de/hotel-aleksandar-in-budva/unterkunft/wohnzimmer/', TemplateView.as_view(template_name='aleksandar/family-room.html')),
    url(r'de/hotel-aleksandar-in-budva/unterkunft/wohnung/', TemplateView.as_view(template_name='aleksandar/large-family-room.html')),
    url(r'de/hotel-aleksandar-in-budva/unterkunft/', TemplateView.as_view(template_name='aleksandar/accommodation.html')),
    url(r'de/hotel-aleksandar-in-budva/restaurants-und-bars/', TemplateView.as_view(template_name='aleksandar/restaurants.html')),
    url(r'de/hotel-aleksandar-in-budva/konferenzraeume/', TemplateView.as_view(template_name='aleksandar/meetings.html')),
    url(r'de/hotel-aleksandar-in-budva/wellness-und-spa/', TemplateView.as_view(template_name='aleksandar/wellness.html')),
    url(r'de/hotel-aleksandar-in-budva/straende-und-pools/', TemplateView.as_view(template_name='aleksandar/beaches.html')),
    url(r'de/hotel-aleksandar-in-budva/lage/', TemplateView.as_view(template_name='aleksandar/location.html')),
    url(r'de/hotel-aleksandar-in-budva/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),

    # /fr pages
    url(r'fr/hotel-aleksandar-a-budva/apercu/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),
    url(r'fr/hotel-aleksandar-a-budva/chambres-et-suites/chambre-double-lits-jumeaux/', TemplateView.as_view(template_name='aleksandar/standard-double-terrace.html')),
    url(r'fr/hotel-aleksandar-a-budva/chambres-et-suites/chambre-double-lits-jumeaux-avec-balcon/', TemplateView.as_view(template_name='aleksandar/standard-double.html')),
    url(r'fr/hotel-aleksandar-a-budva/chambres-et-suites/chambre-confort-avec-balcon/', TemplateView.as_view(template_name='aleksandar/comfort-double.html')),
    url(r'fr/hotel-aleksandar-a-budva/chambres-et-suites/chambre-de-famille/', TemplateView.as_view(template_name='aleksandar/family-room.html')),
    url(r'fr/hotel-aleksandar-a-budva/chambres-et-suites/appartement/', TemplateView.as_view(template_name='aleksandar/large-family-room.html')),
    url(r'fr/hotel-aleksandar-a-budva/chambres-et-suites/', TemplateView.as_view(template_name='aleksandar/accommodation.html')),
    url(r'fr/hotel-aleksandar-a-budva/restaurants-et-bars/', TemplateView.as_view(template_name='aleksandar/restaurants.html')),
    url(r'fr/hotel-aleksandar-a-budva/salles-de-conference/', TemplateView.as_view(template_name='aleksandar/meetings.html')),
    url(r'fr/hotel-aleksandar-a-budva/bien-etre-et-spa/', TemplateView.as_view(template_name='aleksandar/wellness.html')),
    url(r'fr/hotel-aleksandar-a-budva/plages-et-piscines/', TemplateView.as_view(template_name='aleksandar/beaches.html')),
    url(r'fr/hotel-aleksandar-a-budva/localisation/', TemplateView.as_view(template_name='aleksandar/location.html')),
    url(r'fr/hotel-aleksandar-a-budva/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),

    # /ru pages
    url(r'ru/otel-aleksandar-v-budve/obzor/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),
    url(r'ru/otel-aleksandar-v-budve/nomera-i-apartamenty/dvukhmestnyy-nomer/', TemplateView.as_view(template_name='aleksandar/standard-double-terrace.html')),
    url(r'ru/otel-aleksandar-v-budve/nomera-i-apartamenty/dvukhmestnyy-nomer-s-balkonom/', TemplateView.as_view(template_name='aleksandar/standard-double.html')),
    url(r'ru/otel-aleksandar-v-budve/nomera-i-apartamenty/komfortnyy-nomer-s-balkonom/', TemplateView.as_view(template_name='aleksandar/comfort-double.html')),
    url(r'ru/otel-aleksandar-v-budve/nomera-i-apartamenty/gostinaya/', TemplateView.as_view(template_name='aleksandar/family-room.html')),
    url(r'ru/otel-aleksandar-v-budve/nomera-i-apartamenty/apartamenty/', TemplateView.as_view(template_name='aleksandar/large-family-room.html')),
    url(r'ru/otel-aleksandar-v-budve/nomera-i-apartamenty/', TemplateView.as_view(template_name='aleksandar/accommodation.html')),
    url(r'ru/otel-aleksandar-v-budve/restorany-i-bary/', TemplateView.as_view(template_name='aleksandar/restaurants.html')),
    url(r'ru/otel-aleksandar-v-budve/konferents-zaly/', TemplateView.as_view(template_name='aleksandar/meetings.html')),
    url(r'ru/otel-aleksandar-v-budve/sauna-i-spa/', TemplateView.as_view(template_name='aleksandar/wellness.html')),
    url(r'ru/otel-aleksandar-v-budve/plyazhi-i-basseyny/', TemplateView.as_view(template_name='aleksandar/beaches.html')),
    url(r'ru/otel-aleksandar-v-budve/lokaciya/', TemplateView.as_view(template_name='aleksandar/location.html')),
    url(r'ru/otel-aleksandar-v-budve/obzor/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),
    url(r'ru/otel-aleksandar-v-budve/', TemplateView.as_view(template_name='aleksandar/hotel-overview.html')),
    ]
