# Generated by Django 2.2.9 on 2020-02-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePagePricesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palas', models.IntegerField(blank=True, help_text='Palas Starting Price', null=True)),
                ('castellastva', models.IntegerField(blank=True, help_text='Castellastva Starting Price', null=True)),
                ('aleksandar', models.IntegerField(blank=True, help_text='Aleksandar Starting Price', null=True)),
                ('slovenska_plaza', models.IntegerField(blank=True, help_text='Slovenska Starting Price', null=True)),
                ('mogren', models.IntegerField(blank=True, help_text='Mogren Starting Price', null=True)),
                ('crystal_palas', models.IntegerField(blank=True, help_text='Crystal Starting Price', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
