# Generated by Django 2.2.9 on 2020-07-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomodationCtaLinksSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_slovenska_plaza_3_star_accommodation_suite_2_adults', models.URLField(blank=True, help_text='Slovenska *** - Suite (2 Adults)', null=True)),
                ('b_slovenska_plaza_3_star_accommodation_suite_4_adults', models.URLField(blank=True, help_text='Slovenska *** - Suite (4 Adults)', null=True)),
                ('b_slovenska_plaza_3_star_accommodation_sofa_bed', models.URLField(blank=True, help_text='Slovenska *** - Suite with Sofa Bed', null=True)),
                ('b_slovenska_plaza_3_star_accommodation_double_room', models.URLField(blank=True, help_text='Slovenska *** - Double Room', null=True)),
                ('b_slovenska_plaza_3_star_accommodation_special_double_room', models.URLField(blank=True, help_text='Slovenska *** - Special Offer - Standard Double Room', null=True)),
                ('b_slovenska_plaza_4_star_accommodation_suite_2_adults', models.URLField(blank=True, help_text='Slovenska **** - Suite (2 Adults)', null=True)),
                ('b_slovenska_plaza_4_star_accommodation_suite_4_adults', models.URLField(blank=True, help_text='Slovenska **** - Suite (2 Adults)', null=True)),
                ('b_slovenska_plaza_4_star_accommodation_sofa_bed', models.URLField(blank=True, help_text='Slovenska **** -  Suite with Sofa Bed', null=True)),
                ('b_slovenska_plaza_4_star_accommodation_double_room', models.URLField(blank=True, help_text='Slovenska **** - Double Room', null=True)),
                ('b_slovenska_plaza_4_star_accommodation_special_double_room', models.URLField(blank=True, help_text='Slovenska **** - Special Offer - Standard Double Room', null=True)),
                ('b_palas_accommodation_standard_double_room', models.URLField(blank=True, help_text='Palas - Standard Double Room', null=True)),
                ('b_palas_accommodation_standard_double_suite', models.URLField(blank=True, help_text='Palas - Double Suite', null=True)),
                ('b_palas_accommodation_comfort_double_room_sea_view', models.URLField(blank=True, help_text='Palas - Comfort Double Room with Terrace and Sea View', null=True)),
                ('b_palas_accommodation_comfort_double_room_mountain_view', models.URLField(blank=True, help_text='Palas - Comfort Double Room with Terrace and Mountain View', null=True)),
                ('b_palas_lux_accommodation_double_room', models.URLField(blank=True, help_text='Palas Lux - Lux Double Room', null=True)),
                ('b_palas_lux_accommodation_double_room_separate_beds', models.URLField(blank=True, help_text='Palas Lux - Lux Double Room with Separate Beds', null=True)),
                ('b_palas_lux_accommodation_suite_mountain_view', models.URLField(blank=True, help_text='Palas Lux - Lux Suite with Mountain View', null=True)),
                ('b_palas_lux_accommodation_suite_sea_view', models.URLField(blank=True, help_text='Palas - Lux Suite with Sea View', null=True)),
                ('b_aleksandar_standard_double_room_with_terrace', models.URLField(blank=True, help_text='Aleksandar - Standard Double Room With Terrace', null=True)),
                ('b_aleksandar_standard_double_room', models.URLField(blank=True, help_text='Aleksandar - Standard Double Room', null=True)),
                ('b_aleksandar_family_room', models.URLField(blank=True, help_text='Aleksandar - Family room', null=True)),
                ('b_aleksandar_large_family_room', models.URLField(blank=True, help_text='Aleksandar - Large Family Room', null=True)),
                ('b_aleksandar_comfort_double_room', models.URLField(blank=True, help_text='Aleksandar - Comfort Double Room', null=True)),
                ('b_aleksandar_comfort_double_suite', models.URLField(blank=True, help_text='Aleksandar - Comfort Double Suite', null=True)),
                ('b_castellastva_standard_double_room_with_terrace', models.URLField(blank=True, help_text='Castellastva - Standard Double Room With Terrace', null=True)),
                ('b_castellastva_standard_double_room_with_terrace_separate_beds', models.URLField(blank=True, help_text='Castellastva - Standard Double Room With Separate Beds and Terrace', null=True)),
                ('b_castellastva_comfort_double_room', models.URLField(blank=True, help_text='Castellastva - Comfort Double Room', null=True)),
                ('b_castellastva_deluxe_suite_with_balcony', models.URLField(blank=True, help_text='Castellastva - Deluxe Suite With Balcony', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccomodationPricesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_palas', models.IntegerField(blank=True, help_text='Homepage Palas Starting Price', null=True)),
                ('homepage_castellastva', models.IntegerField(blank=True, help_text='Homepage Castellastva Starting Price', null=True)),
                ('homepage_aleksandar', models.IntegerField(blank=True, help_text='Homepage Aleksandar Starting Price', null=True)),
                ('homepage_slovenska_plaza', models.IntegerField(blank=True, help_text='Homepage Slovenska Starting Price', null=True)),
                ('homepage_mogren', models.IntegerField(blank=True, help_text='Homepage Mogren Starting Price', null=True)),
                ('homepage_palas_lux', models.IntegerField(blank=True, help_text='Homepage Palas Lux Starting Price', null=True)),
                ('slovenska_plaza_3_star_accommodation_suite_2_adults', models.IntegerField(blank=True, help_text='Slovenska *** - Suite (2 Adults)', null=True)),
                ('slovenska_plaza_3_star_accommodation_suite_4_adults', models.IntegerField(blank=True, help_text='Slovenska *** - Suite (4 Adults)', null=True)),
                ('slovenska_plaza_3_star_accommodation_sofa_bed', models.IntegerField(blank=True, help_text='Slovenska *** - Suite with Sofa Bed', null=True)),
                ('slovenska_plaza_3_star_accommodation_double_room', models.IntegerField(blank=True, help_text='Slovenska *** - Double Room', null=True)),
                ('slovenska_plaza_3_star_accommodation_special_double_room', models.IntegerField(blank=True, help_text='Slovenska *** - Special Offer - Standard Double Room', null=True)),
                ('slovenska_plaza_4_star_accommodation_suite_2_adults', models.IntegerField(blank=True, help_text='Slovenska **** - Suite (2 Adults)', null=True)),
                ('slovenska_plaza_4_star_accommodation_suite_4_adults', models.IntegerField(blank=True, help_text='Slovenska **** - Suite (2 Adults)', null=True)),
                ('slovenska_plaza_4_star_accommodation_sofa_bed', models.IntegerField(blank=True, help_text='Slovenska **** -  Suite with Sofa Bed', null=True)),
                ('slovenska_plaza_4_star_accommodation_double_room', models.IntegerField(blank=True, help_text='Slovenska **** - Double Room', null=True)),
                ('slovenska_plaza_4_star_accommodation_special_double_room', models.IntegerField(blank=True, help_text='Slovenska **** - Special Offer - Standard Double Room', null=True)),
                ('palas_accommodation_standard_double_room', models.IntegerField(blank=True, help_text='Palas - Standard Double Room', null=True)),
                ('palas_accommodation_standard_double_suite', models.IntegerField(blank=True, help_text='Palas - Double Suite', null=True)),
                ('palas_accommodation_comfort_double_room_sea_view', models.IntegerField(blank=True, help_text='Palas - Comfort Double Room with Terrace and Sea View', null=True)),
                ('palas_accommodation_comfort_double_room_mountain_view', models.IntegerField(blank=True, help_text='Palas - Comfort Double Room with Terrace and Mountain View', null=True)),
                ('palas_lux_accommodation_double_room', models.IntegerField(blank=True, help_text='Palas Lux - Lux Double Room', null=True)),
                ('palas_lux_accommodation_double_room_separate_beds', models.IntegerField(blank=True, help_text='Palas Lux - Lux Double Room with Separate Beds', null=True)),
                ('palas_lux_accommodation_suite_mountain_view', models.IntegerField(blank=True, help_text='Palas Lux - Lux Suite with Mountain View', null=True)),
                ('palas_lux_accommodation_suite_sea_view', models.IntegerField(blank=True, help_text='Palas - Lux Suite with Sea View', null=True)),
                ('aleksandar_standard_double_room_with_terrace', models.IntegerField(blank=True, help_text='Aleksandar - Standard Double Room With Terrace', null=True)),
                ('aleksandar_standard_double_room', models.IntegerField(blank=True, help_text='Aleksandar - Standard Double Room', null=True)),
                ('aleksandar_family_room', models.IntegerField(blank=True, help_text='Aleksandar - Family room', null=True)),
                ('aleksandar_large_family_room', models.IntegerField(blank=True, help_text='Aleksandar - Large Family Room', null=True)),
                ('aleksandar_comfort_double_room', models.IntegerField(blank=True, help_text='Aleksandar - Comfort Double Room', null=True)),
                ('aleksandar_comfort_double_suite', models.IntegerField(blank=True, help_text='Aleksandar - Comfort Double Suite', null=True)),
                ('castellastva_standard_double_room_with_terrace', models.IntegerField(blank=True, help_text='Castellastva - Standard Double Room With Terrace', null=True)),
                ('castellastva_standard_double_room_with_terrace_separate_beds', models.IntegerField(blank=True, help_text='Castellastva - Standard Double Room With Separate Beds and Terrace', null=True)),
                ('castellastva_comfort_double_room', models.IntegerField(blank=True, help_text='Castellastva - Comfort Double Room', null=True)),
                ('castellastva_deluxe_suite_with_balcony', models.IntegerField(blank=True, help_text='Castellastva - Deluxe Suite With Balcony', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HomePagePricesSettings',
        ),
    ]
