# Generated by Django 2.2.9 on 2021-02-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('site_settings', '0002_auto_20200707_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_aleksandar_comfort_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_aleksandar_comfort_double_suite',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_aleksandar_large_family_room',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_aleksandar_standard_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_aleksandar_standard_double_room_with_terrace',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_castellastva_comfort_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_castellastva_standard_double_room_with_terrace',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_castellastva_standard_double_room_with_terrace_separate_beds',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_palas_accommodation_standard_double_suite',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_3_star_accommodation_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_3_star_accommodation_sofa_bed',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_3_star_accommodation_special_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_3_star_accommodation_suite_2_adults',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_3_star_accommodation_suite_4_adults',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_4_star_accommodation_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_4_star_accommodation_sofa_bed',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_4_star_accommodation_special_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_4_star_accommodation_suite_2_adults',
        ),
        migrations.RemoveField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_4_star_accommodation_suite_4_adults',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='aleksandar_comfort_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='aleksandar_comfort_double_suite',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='aleksandar_large_family_room',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='aleksandar_standard_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='aleksandar_standard_double_room_with_terrace',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='castellastva_comfort_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='castellastva_standard_double_room_with_terrace',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='castellastva_standard_double_room_with_terrace_separate_beds',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='palas_accommodation_standard_double_suite',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_3_star_accommodation_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_3_star_accommodation_sofa_bed',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_3_star_accommodation_special_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_3_star_accommodation_suite_2_adults',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_3_star_accommodation_suite_4_adults',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_4_star_accommodation_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_4_star_accommodation_sofa_bed',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_4_star_accommodation_special_double_room',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_4_star_accommodation_suite_2_adults',
        ),
        migrations.RemoveField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_4_star_accommodation_suite_4_adults',
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_aleksandar_apartment',
            field=models.URLField(blank=True, help_text='Aleksandar - Apartment', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_aleksandar_comfort_room_with_balcony',
            field=models.URLField(blank=True, help_text='Aleksandar - Comfort Room with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_aleksandar_double_twin_room',
            field=models.URLField(blank=True, help_text='Aleksandar - Double/Twin Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_aleksandar_double_twin_room_with_balcony',
            field=models.URLField(blank=True, help_text='Aleksandar - Double/Twin Room with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_castellastva_double_room_with_terrace',
            field=models.URLField(blank=True, help_text='Castellastva - Double Room with Terrace/Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_castellastva_family_room',
            field=models.URLField(blank=True, help_text='Castellastva - Family Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_3_star_accommodation_comfort_twin_room',
            field=models.URLField(blank=True, help_text='Slovenska *** - Comfort Twin Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_3_star_accommodation_double_room_balcony',
            field=models.URLField(blank=True, help_text='Slovenska *** - Double/Twin Room with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_3_star_accommodation_double_twin_room',
            field=models.URLField(blank=True, help_text='Slovenska *** - Double/Twin Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_3_star_accommodation_family_apartment',
            field=models.URLField(blank=True, help_text='Slovenska *** - Family Apartment with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_3_star_accommodation_studio_apartment',
            field=models.URLField(blank=True, help_text='Slovenska *** - Studio Apartment with Kitchen', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_4_star_accommodation_comfort_twin_room',
            field=models.URLField(blank=True, help_text='Slovenska **** - Comfort Twin Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_4_star_accommodation_double_room_with_balcony',
            field=models.URLField(blank=True, help_text='Slovenska **** - Double/Twin Room with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_4_star_accommodation_double_twin_room',
            field=models.URLField(blank=True, help_text='Slovenska **** - Double/Twin Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_4_star_accommodation_family_apartment',
            field=models.URLField(blank=True, help_text='Slovenska **** - Family Apartment with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationctalinkssettings',
            name='b_slovenska_plaza_4_star_accommodation_studio_apartment',
            field=models.URLField(blank=True, help_text='Slovenska **** - Studio Apartment', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='aleksandar_apartment',
            field=models.IntegerField(blank=True, help_text='Aleksandar - Apartment', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='aleksandar_comfort_room_with_balcony',
            field=models.IntegerField(blank=True, help_text='Aleksandar - Comfort Room with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='aleksandar_double_twin_room',
            field=models.IntegerField(blank=True, help_text='Aleksandar - Double/Twin Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='aleksandar_double_twin_room_with_balcony',
            field=models.IntegerField(blank=True, help_text='Aleksandar - Double/Twin Room with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='castellastva_double_room_with_terrace',
            field=models.IntegerField(blank=True, help_text='Castellastva - Double Room with Terrace/Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='castellastva_family_room',
            field=models.IntegerField(blank=True, help_text='Castellastva - Family Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_3_star_accommodation_comfort_twin_room',
            field=models.IntegerField(blank=True, help_text='Slovenska *** - Comfort Twin Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_3_star_accommodation_double_room_balcony',
            field=models.IntegerField(blank=True, help_text='Slovenska *** - Double/Twin Room with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_3_star_accommodation_double_twin_room',
            field=models.IntegerField(blank=True, help_text='Slovenska *** - Double/Twin Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_3_star_accommodation_family_apartment',
            field=models.IntegerField(blank=True, help_text='Slovenska *** - Family Apartment with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_3_star_accommodation_studio_apartment',
            field=models.IntegerField(blank=True, help_text='Slovenska *** - Studio Apartment with Kitchen', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_4_star_accommodation_comfort_twin_room',
            field=models.IntegerField(blank=True, help_text='Slovenska **** - Comfort Twin Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_4_star_accommodation_double_room_with_balcony',
            field=models.IntegerField(blank=True, help_text='Slovenska **** - Double/Twin Room with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_4_star_accommodation_double_twin_room',
            field=models.IntegerField(blank=True, help_text='Slovenska **** - Double/Twin Room', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_4_star_accommodation_family_apartment',
            field=models.IntegerField(blank=True, help_text='Slovenska **** - Family Apartment with Balcony', null=True),
        ),
        migrations.AddField(
            model_name='accomodationpricessettings',
            name='slovenska_plaza_4_star_accommodation_studio_apartment',
            field=models.IntegerField(blank=True, help_text='Slovenska **** - Studio Apartment', null=True),
        ),
        migrations.CreateModel(
            name='UpdateAccomodationPricesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_palas', models.IntegerField(blank=True, help_text='Homepage Palas Starting Price', null=True)),
                ('homepage_castellastva', models.IntegerField(blank=True, help_text='Homepage Castellastva Starting Price', null=True)),
                ('homepage_aleksandar', models.IntegerField(blank=True, help_text='Homepage Aleksandar Starting Price', null=True)),
                ('homepage_slovenska_plaza', models.IntegerField(blank=True, help_text='Homepage Slovenska Starting Price', null=True)),
                ('homepage_mogren', models.IntegerField(blank=True, help_text='Homepage Mogren Starting Price', null=True)),
                ('homepage_palas_lux', models.IntegerField(blank=True, help_text='Homepage Palas Lux Starting Price', null=True)),
                ('slovenska_plaza_3_star_accommodation_comfort_twin_room', models.IntegerField(blank=True, help_text='Slovenska *** - Comfort Twin Room', null=True)),
                ('slovenska_plaza_3_star_accommodation_family_apartment', models.IntegerField(blank=True, help_text='Slovenska *** - Family Apartment with Balcony', null=True)),
                ('slovenska_plaza_3_star_accommodation_double_twin_room', models.IntegerField(blank=True, help_text='Slovenska *** - Double/Twin Room', null=True)),
                ('slovenska_plaza_3_star_accommodation_double_room_balcony', models.IntegerField(blank=True, help_text='Slovenska *** - Double/Twin Room with Balcony', null=True)),
                ('slovenska_plaza_3_star_accommodation_studio_apartment', models.IntegerField(blank=True, help_text='Slovenska *** - Studio Apartment with Kitchen', null=True)),
                ('slovenska_plaza_4_star_accommodation_comfort_twin_room', models.IntegerField(blank=True, help_text='Slovenska **** - Comfort Twin Room', null=True)),
                ('slovenska_plaza_4_star_accommodation_studio_apartment', models.IntegerField(blank=True, help_text='Slovenska **** - Studio Apartment', null=True)),
                ('slovenska_plaza_4_star_accommodation_double_twin_room', models.IntegerField(blank=True, help_text='Slovenska **** - Double/Twin Room', null=True)),
                ('slovenska_plaza_4_star_accommodation_double_room_with_balcony', models.IntegerField(blank=True, help_text='Slovenska **** - Double/Twin Room with Balcony', null=True)),
                ('slovenska_plaza_4_star_accommodation_family_apartment', models.IntegerField(blank=True, help_text='Slovenska **** - Family Apartment with Balcony', null=True)),
                ('palas_accommodation_standard_double_room', models.IntegerField(blank=True, help_text='Palas - Standard Double Room', null=True)),
                ('palas_accommodation_comfort_double_room_sea_view', models.IntegerField(blank=True, help_text='Palas - Comfort Double Room with Terrace and Sea View', null=True)),
                ('palas_accommodation_comfort_double_room_mountain_view', models.IntegerField(blank=True, help_text='Palas - Comfort Double Room with Terrace and Mountain View', null=True)),
                ('palas_lux_accommodation_double_room', models.IntegerField(blank=True, help_text='Palas Lux - Lux Double Room', null=True)),
                ('palas_lux_accommodation_double_room_separate_beds', models.IntegerField(blank=True, help_text='Palas Lux - Lux Double Room with Separate Beds', null=True)),
                ('palas_lux_accommodation_suite_mountain_view', models.IntegerField(blank=True, help_text='Palas Lux - Lux Suite with Mountain View', null=True)),
                ('palas_lux_accommodation_suite_sea_view', models.IntegerField(blank=True, help_text='Palas - Lux Suite with Sea View', null=True)),
                ('aleksandar_double_twin_room', models.IntegerField(blank=True, help_text='Aleksandar - Double/Twin Room', null=True)),
                ('aleksandar_double_twin_room_with_balcony', models.IntegerField(blank=True, help_text='Aleksandar - Double/Twin Room with Balcony', null=True)),
                ('aleksandar_family_room', models.IntegerField(blank=True, help_text='Aleksandar - Family room', null=True)),
                ('aleksandar_apartment', models.IntegerField(blank=True, help_text='Aleksandar - Apartment', null=True)),
                ('aleksandar_comfort_room_with_balcony', models.IntegerField(blank=True, help_text='Aleksandar - Comfort Room with Balcony', null=True)),
                ('castellastva_family_room', models.IntegerField(blank=True, help_text='Castellastva - Family Room', null=True)),
                ('castellastva_double_room_with_terrace', models.IntegerField(blank=True, help_text='Castellastva - Double Room with Terrace/Balcony', null=True)),
                ('castellastva_deluxe_suite_with_balcony', models.IntegerField(blank=True, help_text='Castellastva - Deluxe Suite With Balcony', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateAccomodationCtaLinksSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_slovenska_plaza_3_star_accommodation_comfort_twin_room', models.URLField(blank=True, help_text='Slovenska *** - Comfort Twin Room', null=True)),
                ('b_slovenska_plaza_3_star_accommodation_family_apartment', models.URLField(blank=True, help_text='Slovenska *** - Family Apartment with Balcony', null=True)),
                ('b_slovenska_plaza_3_star_accommodation_double_twin_room', models.URLField(blank=True, help_text='Slovenska *** - Double/Twin Room', null=True)),
                ('b_slovenska_plaza_3_star_accommodation_double_room_balcony', models.URLField(blank=True, help_text='Slovenska *** - Double/Twin Room with Balcony', null=True)),
                ('b_slovenska_plaza_3_star_accommodation_studio_apartment', models.URLField(blank=True, help_text='Slovenska *** - Studio Apartment with Kitchen', null=True)),
                ('b_slovenska_plaza_4_star_accommodation_comfort_twin_room', models.URLField(blank=True, help_text='Slovenska **** - Comfort Twin Room', null=True)),
                ('b_slovenska_plaza_4_star_accommodation_studio_apartment', models.URLField(blank=True, help_text='Slovenska **** - Studio Apartment', null=True)),
                ('b_slovenska_plaza_4_star_accommodation_double_twin_room', models.URLField(blank=True, help_text='Slovenska **** - Double/Twin Room', null=True)),
                ('b_slovenska_plaza_4_star_accommodation_double_room_with_balcony', models.URLField(blank=True, help_text='Slovenska **** - Double/Twin Room with Balcony', null=True)),
                ('b_slovenska_plaza_4_star_accommodation_family_apartment', models.URLField(blank=True, help_text='Slovenska **** - Family Apartment with Balcony', null=True)),
                ('b_palas_accommodation_standard_double_room', models.URLField(blank=True, help_text='Palas - Standard Double Room', null=True)),
                ('b_palas_accommodation_comfort_double_room_sea_view', models.URLField(blank=True, help_text='Palas - Comfort Double Room with Terrace and Sea View', null=True)),
                ('b_palas_accommodation_comfort_double_room_mountain_view', models.URLField(blank=True, help_text='Palas - Comfort Double Room with Terrace and Mountain View', null=True)),
                ('b_palas_lux_accommodation_double_room', models.URLField(blank=True, help_text='Palas Lux - Lux Double Room', null=True)),
                ('b_palas_lux_accommodation_double_room_separate_beds', models.URLField(blank=True, help_text='Palas Lux - Lux Double Room with Separate Beds', null=True)),
                ('b_palas_lux_accommodation_suite_mountain_view', models.URLField(blank=True, help_text='Palas Lux - Lux Suite with Mountain View', null=True)),
                ('b_palas_lux_accommodation_suite_sea_view', models.URLField(blank=True, help_text='Palas - Lux Suite with Sea View', null=True)),
                ('b_aleksandar_double_twin_room', models.URLField(blank=True, help_text='Aleksandar - Double/Twin Room', null=True)),
                ('b_aleksandar_double_twin_room_with_balcony', models.URLField(blank=True, help_text='Aleksandar - Double/Twin Room with Balcony', null=True)),
                ('b_aleksandar_family_room', models.URLField(blank=True, help_text='Aleksandar - Family room', null=True)),
                ('b_aleksandar_apartment', models.URLField(blank=True, help_text='Aleksandar - Apartment', null=True)),
                ('b_aleksandar_comfort_room_with_balcony', models.URLField(blank=True, help_text='Aleksandar - Comfort Room with Balcony', null=True)),
                ('b_castellastva_family_room', models.URLField(blank=True, help_text='Castellastva - Family Room', null=True)),
                ('b_castellastva_double_room_with_terrace', models.URLField(blank=True, help_text='Castellastva - Double Room with Terrace/Balcony', null=True)),
                ('b_castellastva_deluxe_suite_with_balcony', models.URLField(blank=True, help_text='Castellastva - Deluxe Suite With Balcony', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
