# Generated by Django 2.2.9 on 2020-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblogpage',
            name='subtitle',
            field=models.CharField(help_text='Podnaslov od najvise 400 karaktera - prikazace se u karticama na pocetnoj stranici', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='articleblogpage',
            name='subtitle_de',
            field=models.CharField(help_text='Podnaslov od najvise 400 karaktera - prikazace se u karticama na pocetnoj stranici', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='articleblogpage',
            name='subtitle_en',
            field=models.CharField(help_text='Podnaslov od najvise 400 karaktera - prikazace se u karticama na pocetnoj stranici', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='articleblogpage',
            name='subtitle_fr',
            field=models.CharField(help_text='Podnaslov od najvise 400 karaktera - prikazace se u karticama na pocetnoj stranici', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='articleblogpage',
            name='subtitle_it',
            field=models.CharField(help_text='Podnaslov od najvise 400 karaktera - prikazace se u karticama na pocetnoj stranici', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='articleblogpage',
            name='subtitle_me',
            field=models.CharField(help_text='Podnaslov od najvise 400 karaktera - prikazace se u karticama na pocetnoj stranici', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='articleblogpage',
            name='subtitle_ru',
            field=models.CharField(help_text='Podnaslov od najvise 400 karaktera - prikazace se u karticama na pocetnoj stranici', max_length=400, null=True),
        ),
    ]
