# Generated by Django 2.2.9 on 2021-02-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200707_1152'),
        ('blog', '0002_auto_20200508_1226'),
    ]

    operations = [
    ]
