from django.conf.urls import url

from django.views.generic import TemplateView

urlpatterns = [

    # /me pages
    url(r'me/hotel-slovenska-plaza-u-budvi/pregled-hotela/',
        TemplateView.as_view(template_name='slovenska/hotel-overview.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/restorani/',
        TemplateView.as_view(template_name='slovenska/restaurants.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/plaze-i-bazeni/',
        TemplateView.as_view(template_name='slovenska/beaches.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/aktivnosti/',
        TemplateView.as_view(template_name='slovenska/activities.html')),
    # url(r'me/hotel-slovenska-plaza-u-budvi/eco-label-sertifikat/',
    #     TemplateView.as_view(template_name='slovenska/eco-label.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/lokacija/',
        TemplateView.as_view(template_name='slovenska/location.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-3-zvjezdice/comfort-dvokrevetna-soba-sa-terasom/',
        TemplateView.as_view(template_name='slovenska/suite2.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-3-zvjezdice/porodicni-apartman-sa-terasom/',
        TemplateView.as_view(template_name='slovenska/suite4.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-3-zvjezdice/dvokrevetna-soba/',
        TemplateView.as_view(template_name='slovenska/sofa-bed.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-3-zvjezdice/dvokrevetna-soba-sa-terasom/',
        TemplateView.as_view(template_name='slovenska/double-room.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-3-zvjezdice/studio-apartman-sa-kuhinjom/',
        TemplateView.as_view(template_name='slovenska/special-double-room.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-4-zvjezdice/comfort-dvokrevetna-soba/',
        TemplateView.as_view(template_name='slovenska/suite2-4.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-4-zvjezdice/studio-apartman/',
        TemplateView.as_view(template_name='slovenska/suite4-4.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-4-zvjezdice/dvokrevetna-soba/',
        TemplateView.as_view(template_name='slovenska/sofa-bed-4.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-4-zvjezdice/dvokrevetna-soba-sa-terasom/',
        TemplateView.as_view(template_name='slovenska/double-room-4.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-4-zvjezdice/porodicni-apartman-sa-terasom/',
        TemplateView.as_view(template_name='slovenska/special-double-room-4.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-3-zvjezdice/',
        TemplateView.as_view(template_name='slovenska/accommodation-3.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-4-zvjezdice/',
        TemplateView.as_view(template_name='slovenska/accommodation-4.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/tenis/',
        TemplateView.as_view(template_name='slovenska/tennis.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/',
        TemplateView.as_view(template_name='slovenska/hotel-overview.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-3-zvjezdice/',
        TemplateView.as_view(template_name='slovenska/accommodation-3.html')),
    url(r'me/hotel-slovenska-plaza-u-budvi/smjestaj-4-zvjezdice/',
        TemplateView.as_view(template_name='slovenska/accommodation-4.html')),

    # /en pages
    url(r'en/hotel-slovenska-plaza-in-budva/overview/',
        TemplateView.as_view(template_name='slovenska/hotel-overview.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/restaurants-and-bars/',
        TemplateView.as_view(template_name='slovenska/restaurants.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/beaches-and-pools/',
        TemplateView.as_view(template_name='slovenska/beaches.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/hotel-activity-programmes/',
        TemplateView.as_view(template_name='slovenska/activities.html')),
    # url(r'en/hotel-slovenska-plaza-in-budva/eco-label-certificate/',
    #     TemplateView.as_view(template_name='slovenska/eco-label.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/location/',
        TemplateView.as_view(template_name='slovenska/location.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/3-star-guest-rooms/comfort-twin-room-extra-bed/',
        TemplateView.as_view(template_name='slovenska/suite2.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/3-star-guest-rooms/family-apartment-balcony/',
        TemplateView.as_view(template_name='slovenska/suite4.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/3-star-guest-rooms/double-twin-room/',
        TemplateView.as_view(template_name='slovenska/sofa-bed.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/3-star-guest-rooms/double-twin-room-balcony/',
        TemplateView.as_view(template_name='slovenska/double-room.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/3-star-guest-rooms/studio-apartment-kitchen/',
        TemplateView.as_view(template_name='slovenska/special-double-room.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/4-star-guest-rooms/comfort-twin-room/',
        TemplateView.as_view(template_name='slovenska/suite2-4.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/4-star-guest-rooms/studio-apartment/',
        TemplateView.as_view(template_name='slovenska/suite4-4.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/4-star-guest-rooms/double-twin-room/',
        TemplateView.as_view(template_name='slovenska/sofa-bed-4.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/4-star-guest-rooms/double-twin-room-balcony/',
        TemplateView.as_view(template_name='slovenska/double-room-4.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/4-star-guest-rooms/family-apartment-balcony/',
        TemplateView.as_view(template_name='slovenska/special-double-room-4.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/3-star-guest-rooms/',
        TemplateView.as_view(template_name='slovenska/accommodation-3.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/4-star-guest-rooms/',
        TemplateView.as_view(template_name='slovenska/accommodation-4.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/tennis-resort/',
        TemplateView.as_view(template_name='slovenska/tennis.html')),
    url(r'en/hotel-slovenska-plaza-in-budva/',
        TemplateView.as_view(template_name='slovenska/hotel-overview.html')),

    # /it pages
    url(r'it/hotel-slovenska-plaza-a-budva/informazioni-generali/', TemplateView.as_view(template_name='slovenska/hotel-overview.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/ristoranti-e-bar/', TemplateView.as_view(template_name='slovenska/restaurants.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/spiagge-e-piscine/', TemplateView.as_view(template_name='slovenska/beaches.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/attività-del-hotel/', TemplateView.as_view(template_name='slovenska/activities.html')),
    # url(r'it/hotel-slovenska-plaza-a-budva/certificato-ecologico/', TemplateView.as_view(template_name='slovenska/eco-label.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/posizione/', TemplateView.as_view(template_name='slovenska/location.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-3-stelle/camera-doppia-comfort-con-letto-aggiunto/', TemplateView.as_view(template_name='slovenska/suite2.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-3-stelle/appartamento-familiare-con-balcone/', TemplateView.as_view(template_name='slovenska/suite4.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-3-stelle/camera-matrimoniale-doppia/', TemplateView.as_view(template_name='slovenska/sofa-bed.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-3-stelle/camera-matrimoniale-doppia-con-balcone/', TemplateView.as_view(template_name='slovenska/double-room.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-3-stelle/monolocale-con-cucina/', TemplateView.as_view(template_name='slovenska/special-double-room.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-4-stelle/camera-doppia-comfort/', TemplateView.as_view(template_name='slovenska/suite2-4.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-4-stelle/monolocale/', TemplateView.as_view(template_name='slovenska/suite4-4.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-4-stelle/camera-matrimoniale-doppia/', TemplateView.as_view(template_name='slovenska/sofa-bed-4.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-4-stelle/camera-matrimoniale-doppia-con-balcone/', TemplateView.as_view(template_name='slovenska/double-room-4.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-4-stelle/appartamento-familiare-con-balcone/', TemplateView.as_view(template_name='slovenska/special-double-room-4.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-3-stelle/', TemplateView.as_view(template_name='slovenska/accommodation-3.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/alloggi-4-stelle/', TemplateView.as_view(template_name='slovenska/accommodation-4.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/tennis/',
        TemplateView.as_view(template_name='slovenska/tennis.html')),
    url(r'it/hotel-slovenska-plaza-a-budva/',TemplateView.as_view(template_name='slovenska/hotel-overview.html')),

    # /de pages
    url(r'de/hotel-slovenska-plaza-in-budva/hoteluebersicht/',
        TemplateView.as_view(template_name='slovenska/hotel-overview.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/restaurants-und-bars/',
        TemplateView.as_view(template_name='slovenska/restaurants.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/straende-und-pools/',
        TemplateView.as_view(template_name='slovenska/beaches.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/hotel-activity-programmes/',
        TemplateView.as_view(template_name='slovenska/activities.html')),
    # url(r'de/hotel-slovenska-plaza-in-budva/eco-label-zertifikat/',
    #     TemplateView.as_view(template_name='slovenska/eco-label.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/lage/',
        TemplateView.as_view(template_name='slovenska/location.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/3-sterne-unterkunft/komfort-zweibettzimmer-mit-zustellbett/',
        TemplateView.as_view(template_name='slovenska/suite2.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/3-sterne-unterkunft/familienwohnung-mit-balkon/',
        TemplateView.as_view(template_name='slovenska/suite4.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/3-sterne-unterkunft/doppel-zweibettzimmer/',
        TemplateView.as_view(template_name='slovenska/sofa-bed.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/3-sterne-unterkunft/doppel-zweibettzimmer-mit-balkon/',
        TemplateView.as_view(template_name='slovenska/double-room.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/3-sterne-unterkunft/studio-apartment-mit-küche/',
        TemplateView.as_view(template_name='slovenska/special-double-room.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/4-sterne-unterkunft/komfort-zweibettzimmer/',
        TemplateView.as_view(template_name='slovenska/suite2-4.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/4-sterne-unterkunft/studio-apartment/',
        TemplateView.as_view(template_name='slovenska/suite4-4.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/4-sterne-unterkunft/doppel-zweibettzimmer/',
        TemplateView.as_view(template_name='slovenska/sofa-bed-4.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/4-sterne-unterkunft/doppel-zweibettzimmer-mit-balkon/',
        TemplateView.as_view(template_name='slovenska/double-room-4.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/4-sterne-unterkunft/familienwohnung-mit-balkon/',
        TemplateView.as_view(template_name='slovenska/special-double-room-4.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/3-sterne-unterkunft/',
        TemplateView.as_view(template_name='slovenska/accommodation-3.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/4-sterne-unterkunft/',
        TemplateView.as_view(template_name='slovenska/accommodation-4.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/tennis/',
        TemplateView.as_view(template_name='slovenska/tennis.html')),
    url(r'de/hotel-slovenska-plaza-in-budva/',
        TemplateView.as_view(template_name='slovenska/hotel-overview.html')),

    # /fr pages
    url(r'fr/hotel-slovenska-plaza-a-budva/apercu/', TemplateView.as_view(template_name='slovenska/hotel-overview.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/restaurants-et-bars/', TemplateView.as_view(template_name='slovenska/restaurants.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/plages-et-piscines/', TemplateView.as_view(template_name='slovenska/beaches.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/programmes-d-activites-hotelieres/', TemplateView.as_view(template_name='slovenska/activities.html')),
    # url(r'fr/hotel-slovenska-plaza-a-budva/eco-label-certificat/', TemplateView.as_view(template_name='slovenska/eco-label.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/localisation/',TemplateView.as_view(template_name='slovenska/location.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-3-etoiles/chambre-twin-confort-avec-lit-supplémentaire/',TemplateView.as_view(template_name='slovenska/suite2.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-3-etoiles/appartement-familial-avec-balcon/',TemplateView.as_view(template_name='slovenska/suite4.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-3-etoiles/chambre-double-lits-jumeaux/',TemplateView.as_view(template_name='slovenska/sofa-bed.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-3-etoiles/chambre-double-lits-jumeaux-avec-balcon/',TemplateView.as_view(template_name='slovenska/double-room.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-3-etoiles/studio-avec-cuisine/',TemplateView.as_view(template_name='slovenska/special-double-room.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-4-etoiles/chambre-twin-confort/',TemplateView.as_view(template_name='slovenska/suite2-4.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-4-etoiles/studio/',TemplateView.as_view(template_name='slovenska/suite4-4.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-4-etoiles/chambre-double-lits-jumeaux/',TemplateView.as_view(template_name='slovenska/sofa-bed-4.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-4-etoiles/chambre-double-lits-jumeaux-avec-balcon/',TemplateView.as_view(template_name='slovenska/double-room-4.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-4-etoiles/appartement-familial-avec-balcon/',TemplateView.as_view(template_name='slovenska/special-double-room-4.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-3-etoiles/', TemplateView.as_view(template_name='slovenska/accommodation-3.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/chambres-d-hotes-4-etoiles/', TemplateView.as_view(template_name='slovenska/accommodation-4.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/tennis/',
        TemplateView.as_view(template_name='slovenska/tennis.html')),
    url(r'fr/hotel-slovenska-plaza-a-budva/', TemplateView.as_view(template_name='slovenska/hotel-overview.html')),



    # /ru pages
    url(r'ru/otel-slovenskiy-plyazh-v-budve/obzor/', TemplateView.as_view(template_name='slovenska/hotel-overview.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/restorany-i-bary/', TemplateView.as_view(template_name='slovenska/restaurants.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/plyazhi-i-basseyny/', TemplateView.as_view(template_name='slovenska/beaches.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/deyatelnost/', TemplateView.as_view(template_name='slovenska/activities.html')),
    # url(r'ru/otel-slovenskiy-plyazh-v-budve/eco-leybl-sertifikat/', TemplateView.as_view(template_name='slovenska/eco-label.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/lokaciya/',TemplateView.as_view(template_name='slovenska/location.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/3-zvezdochnyye-nomera/dvukhmestnyy-nomer-komfort/',TemplateView.as_view(template_name='slovenska/suite2.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/3-zvezdochnyye-nomera/semeynaya-kvartira-s-balkonom/',TemplateView.as_view(template_name='slovenska/suite4.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/3-zvezdochnyye-nomera/dvukhmestnyy-nomer/',TemplateView.as_view(template_name='slovenska/sofa-bed.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/3-zvezdochnyye-nomera/dvukhmestnyy-nomer-s-balkonom/',TemplateView.as_view(template_name='slovenska/double-room.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/3-zvezdochnyye-nomera/odnokomnatnaya-kvartira-s-kukhney/',TemplateView.as_view(template_name='slovenska/special-double-room.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/4-zvezdochnyye-nomera/kvartira-studiya/',TemplateView.as_view(template_name='slovenska/suite4-4.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/4-zvezdochnyye-nomera/dvukhmestnyy-nomer-komfort/',TemplateView.as_view(template_name='slovenska/suite2-4.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/4-zvezdochnyye-nomera/dvukhmestnyy-nomer/',TemplateView.as_view(template_name='slovenska/sofa-bed-4.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/4-zvezdochnyye-nomera/dvukhmestnyy-nomer-s-balkonom/',TemplateView.as_view(template_name='slovenska/double-room-4.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/4-zvezdochnyye-nomera/semeynaya-kvartira-s-balkonom/',TemplateView.as_view(template_name='slovenska/special-double-room-4.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/3-zvezdochnyye-nomera/', TemplateView.as_view(template_name='slovenska/accommodation-3.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/4-zvezdochnyye-nomera/', TemplateView.as_view(template_name='slovenska/accommodation-4.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/tennis/',
        TemplateView.as_view(template_name='slovenska/tennis.html')),
    url(r'ru/otel-slovenskiy-plyazh-v-budve/', TemplateView.as_view(template_name='slovenska/hotel-overview.html')),






    ]
